import { CompanyInvestorPropertyRow } from "@/lib/companyInvestors";

export const demoInvestors: CompanyInvestorPropertyRow[] = [
    {
        id: "inv-1",
        profile_id: "prof-1",
        full_name: "Dragan Petrović",
        email: "dragan.p@example.com",
        phone: "+381 61 772 1122",
        investor_type: "buyer",
        created_at: "2024-01-10T10:00:00Z",
        building_id: "1",
        building_name: "Avala Resort",
        block: "Block A",
        unit: "A-101",
        area_m2: 65.5,
        delivery_period: "Q4 2024",
        purchase_value: 120000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-2",
        profile_id: "prof-2",
        full_name: "Jelena Jovanović",
        email: "jelena.j@example.com",
        phone: "+381 62 334 5566",
        investor_type: "buyer",
        created_at: "2024-01-12T11:00:00Z",
        building_id: "1",
        building_name: "Avala Resort",
        block: "Block A",
        unit: "A-102",
        area_m2: 42.0,
        delivery_period: "Q4 2024",
        purchase_value: 85000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-3",
        profile_id: "prof-3",
        full_name: "Marko Marković",
        email: "marko.m@example.com",
        phone: "+381 63 998 7766",
        investor_type: "buyer",
        created_at: "2024-01-15T09:30:00Z",
        building_id: "1",
        building_name: "Avala Resort",
        block: "Block B",
        unit: "B-201",
        area_m2: 88.5,
        delivery_period: "Q4 2024",
        purchase_value: 165000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-4",
        profile_id: "prof-4",
        full_name: "Milica Đorđević",
        email: "milica.d@example.com",
        phone: "+381 64 112 2334",
        investor_type: "buyer",
        created_at: "2024-01-20T14:45:00Z",
        building_id: "1",
        building_name: "Avala Resort",
        block: "Block B",
        unit: "B-202",
        area_m2: 55.0,
        delivery_period: "Q4 2024",
        purchase_value: 105000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-5",
        profile_id: "prof-5",
        full_name: "Nikola Nikolić",
        email: "nikola.n@example.com",
        phone: "+381 65 556 6677",
        investor_type: "buyer",
        created_at: "2024-02-01T10:15:00Z",
        building_id: "2",
        building_name: "Skyline Plaza",
        block: "Tower East",
        unit: "E-1004",
        area_m2: 72.0,
        delivery_period: "Q2 2025",
        purchase_value: 210000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-6",
        profile_id: "prof-6",
        full_name: "Ivana Stanković",
        email: "ivana.s@example.com",
        phone: "+381 61 223 3344",
        investor_type: "buyer",
        created_at: "2024-02-03T16:20:00Z",
        building_id: "2",
        building_name: "Skyline Plaza",
        block: "Tower East",
        unit: "E-1005",
        area_m2: 94.0,
        delivery_period: "Q2 2025",
        purchase_value: 280000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-7",
        profile_id: "prof-7",
        full_name: "Goran Simić",
        email: "goran.s@example.com",
        phone: "+381 62 887 7766",
        investor_type: "buyer",
        created_at: "2024-02-10T08:50:00Z",
        building_id: "2",
        building_name: "Skyline Plaza",
        block: "Tower West",
        unit: "W-502",
        area_m2: 50.5,
        delivery_period: "Q2 2025",
        purchase_value: 155000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-8",
        profile_id: "prof-8",
        full_name: "Ana Pavlović",
        email: "ana.p@example.com",
        phone: "+381 63 111 2222",
        investor_type: "buyer",
        created_at: "2024-02-15T12:10:00Z",
        building_id: "2",
        building_name: "Skyline Plaza",
        block: "Tower West",
        unit: "W-503",
        area_m2: 120.0,
        delivery_period: "Q2 2025",
        purchase_value: 340000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-9",
        profile_id: "prof-9",
        full_name: "Bojan Lukić",
        email: "bojan.l@example.com",
        phone: "+382 67 112 233",
        investor_type: "buyer",
        created_at: "2024-02-20T11:30:00Z",
        building_id: "1",
        building_name: "Avala Resort",
        block: "Block C",
        unit: "C-301",
        area_m2: 77.0,
        delivery_period: "Q4 2024",
        purchase_value: 145000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-10",
        profile_id: "prof-10",
        full_name: "Maja Kovačević",
        email: "maja.k@example.com",
        phone: "+382 68 445 566",
        investor_type: "buyer",
        created_at: "2024-02-25T15:20:00Z",
        building_id: "1",
        building_name: "Avala Resort",
        block: "Block C",
        unit: "C-302",
        area_m2: 60.0,
        delivery_period: "Q4 2024",
        purchase_value: 115000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-11",
        profile_id: "prof-11",
        full_name: "Zoran Stefanović",
        email: "zoran.s@example.com",
        phone: "+381 61 998 8877",
        investor_type: "buyer",
        created_at: "2024-03-01T09:40:00Z",
        building_id: "4",
        building_name: "Horizon Towers",
        block: "Tower A",
        unit: "A-504",
        area_m2: 82.5,
        delivery_period: "Q1 2026",
        purchase_value: 235000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-12",
        profile_id: "prof-12",
        full_name: "Katarina Ilić",
        email: "katarina.i@example.com",
        phone: "+381 62 112 3344",
        investor_type: "buyer",
        created_at: "2024-03-05T13:15:00Z",
        building_id: "4",
        building_name: "Horizon Towers",
        block: "Tower A",
        unit: "A-505",
        area_m2: 55.0,
        delivery_period: "Q1 2026",
        purchase_value: 160000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-13",
        profile_id: "prof-13",
        full_name: "Dejan Savić",
        email: "dejan.s@example.com",
        phone: "+381 63 445 6677",
        investor_type: "buyer",
        created_at: "2024-03-10T10:50:00Z",
        building_id: "4",
        building_name: "Horizon Towers",
        block: "Tower B",
        unit: "B-1201",
        area_m2: 95.0,
        delivery_period: "Q1 2026",
        purchase_value: 295000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-14",
        profile_id: "prof-14",
        full_name: "Tamara Lazarević",
        email: "tamara.l@example.com",
        phone: "+381 64 889 9900",
        investor_type: "buyer",
        created_at: "2024-03-12T16:30:00Z",
        building_id: "4",
        building_name: "Horizon Towers",
        block: "Tower B",
        unit: "B-1202",
        area_m2: 70.0,
        delivery_period: "Q1 2026",
        purchase_value: 205000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-15",
        profile_id: "prof-15",
        full_name: "Luka Popović",
        email: "luka.p@example.com",
        phone: "+381 65 223 4455",
        investor_type: "buyer",
        created_at: "2024-03-15T09:10:00Z",
        building_id: "4",
        building_name: "Horizon Towers",
        block: "Tower C",
        unit: "C-101",
        area_m2: 135.0,
        delivery_period: "Q1 2026",
        purchase_value: 410000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-16",
        profile_id: "prof-16",
        full_name: "Elena Todorović",
        email: "elena.t@example.com",
        phone: "+381 61 334 5566",
        investor_type: "buyer",
        created_at: "2024-03-20T14:25:00Z",
        building_id: "4",
        building_name: "Horizon Towers",
        block: "Tower C",
        unit: "C-102",
        area_m2: 45.0,
        delivery_period: "Q1 2026",
        purchase_value: 140000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-17",
        profile_id: "prof-17",
        full_name: "Miloš Marić",
        email: "milos.m@example.com",
        phone: "+381 62 112 2334",
        investor_type: "buyer",
        created_at: "2024-03-25T11:40:00Z",
        building_id: "1",
        building_name: "Avala Resort",
        block: "Block A",
        unit: "A-201",
        area_m2: 52.0,
        delivery_period: "Q4 2024",
        purchase_value: 98000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-18",
        profile_id: "prof-18",
        full_name: "Sara Bogdanović",
        email: "sara.b@example.com",
        phone: "+381 63 667 7788",
        investor_type: "buyer",
        created_at: "2024-04-01T10:05:00Z",
        building_id: "1",
        building_name: "Avala Resort",
        block: "Block A",
        unit: "A-202",
        area_m2: 75.0,
        delivery_period: "Q4 2024",
        purchase_value: 138000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-19",
        profile_id: "prof-19",
        full_name: "Viktor Vasić",
        email: "viktor.v@example.com",
        phone: "+381 64 223 3344",
        investor_type: "buyer",
        created_at: "2024-04-05T09:15:00Z",
        building_id: "2",
        building_name: "Skyline Plaza",
        block: "Tower East",
        unit: "E-801",
        area_m2: 64.0,
        delivery_period: "Q2 2025",
        purchase_value: 185000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-20",
        profile_id: "prof-20",
        full_name: "Sofija Ristić",
        email: "sofija.r@example.com",
        phone: "+381 65 998 8800",
        investor_type: "buyer",
        created_at: "2024-04-08T16:50:00Z",
        building_id: "2",
        building_name: "Skyline Plaza",
        block: "Tower East",
        unit: "E-802",
        area_m2: 82.0,
        delivery_period: "Q2 2025",
        purchase_value: 235000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-21",
        profile_id: "prof-21",
        full_name: "Aleksandar Vuković",
        email: "aleksandar.v@example.com",
        phone: "+381 61 772 1222",
        investor_type: "buyer",
        created_at: "2024-04-12T13:10:00Z",
        building_id: "2",
        building_name: "Skyline Plaza",
        block: "Tower West",
        unit: "W-304",
        area_m2: 48.0,
        delivery_period: "Q2 2025",
        purchase_value: 142000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-22",
        profile_id: "prof-22",
        full_name: "Nina Marković",
        email: "nina.m@example.com",
        phone: "+381 62 112 3322",
        investor_type: "buyer",
        created_at: "2024-04-15T10:30:00Z",
        building_id: "2",
        building_name: "Skyline Plaza",
        block: "Tower West",
        unit: "W-305",
        area_m2: 105.0,
        delivery_period: "Q2 2025",
        purchase_value: 305000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-23",
        profile_id: "prof-23",
        full_name: "Petar Perić",
        email: "petar.p@example.com",
        phone: "+381 63 665 5544",
        investor_type: "buyer",
        created_at: "2024-04-20T09:45:00Z",
        building_id: "3",
        building_name: "Villa Serenity",
        block: "Villa 1",
        unit: "V1-A",
        area_m2: 240.0,
        delivery_period: "Completed",
        purchase_value: 850000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-24",
        profile_id: "prof-24",
        full_name: "Jovana Jović",
        email: "jovana.j@example.com",
        phone: "+381 64 221 1100",
        investor_type: "buyer",
        created_at: "2024-04-25T14:15:00Z",
        building_id: "3",
        building_name: "Villa Serenity",
        block: "Villa 2",
        unit: "V2-B",
        area_m2: 215.0,
        delivery_period: "Completed",
        purchase_value: 780000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-25",
        profile_id: "prof-25",
        full_name: "Filip Filipović",
        email: "filip.f@example.com",
        phone: "+381 65 334 4455",
        investor_type: "buyer",
        created_at: "2024-05-01T10:55:00Z",
        building_id: "3",
        building_name: "Villa Serenity",
        block: "Villa 3",
        unit: "V3-C",
        area_m2: 265.0,
        delivery_period: "Completed",
        purchase_value: 950000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-26",
        profile_id: "prof-26",
        full_name: "Dunja Dimitrijević",
        email: "dunja.d@example.com",
        phone: "+381 61 778 8899",
        investor_type: "buyer",
        created_at: "2024-05-05T15:25:00Z",
        building_id: "1",
        building_name: "Avala Resort",
        block: "Block B",
        unit: "B-401",
        area_m2: 68.0,
        delivery_period: "Q4 2024",
        purchase_value: 128000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-27",
        profile_id: "prof-27",
        full_name: "Nemanja Nedeljković",
        email: "nemanja.n@example.com",
        phone: "+381 62 112 2233",
        investor_type: "buyer",
        created_at: "2024-05-10T11:40:00Z",
        building_id: "1",
        building_name: "Avala Resort",
        block: "Block B",
        unit: "B-402",
        area_m2: 90.0,
        delivery_period: "Q4 2024",
        purchase_value: 168000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-28",
        profile_id: "prof-28",
        full_name: "Teodora Tomić",
        email: "teodora.t@example.com",
        phone: "+381 63 445 5566",
        investor_type: "buyer",
        created_at: "2024-05-15T09:10:00Z",
        building_id: "2",
        building_name: "Skyline Plaza",
        block: "Tower West",
        unit: "W-1204",
        area_m2: 58.0,
        delivery_period: "Q2 2025",
        purchase_value: 175000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-29",
        profile_id: "prof-29",
        full_name: "Uroš Uzunović",
        email: "uros.u@example.com",
        phone: "+381 64 667 7788",
        investor_type: "buyer",
        created_at: "2024-05-20T14:50:00Z",
        building_id: "2",
        building_name: "Skyline Plaza",
        block: "Tower West",
        unit: "W-1205",
        area_m2: 150.0,
        delivery_period: "Q2 2025",
        purchase_value: 450000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-30",
        profile_id: "prof-30",
        full_name: "Olivera Ostojić",
        email: "olivera.o@example.com",
        phone: "+381 65 112 2233",
        investor_type: "buyer",
        created_at: "2024-05-25T10:15:00Z",
        building_id: "4",
        building_name: "Horizon Towers",
        block: "Tower A",
        unit: "A-801",
        area_m2: 70.0,
        delivery_period: "Q1 2026",
        purchase_value: 198000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-31",
        profile_id: "prof-31",
        full_name: "Lazar Lončar",
        email: "lazar.l@example.com",
        phone: "+381 61 334 4455",
        investor_type: "buyer",
        created_at: "2024-06-01T09:30:00Z",
        building_id: "4",
        building_name: "Horizon Towers",
        block: "Tower A",
        unit: "A-802",
        area_m2: 60.0,
        delivery_period: "Q1 2026",
        purchase_value: 172000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-32",
        profile_id: "prof-32",
        full_name: "Bojana Blagojević",
        email: "bojana.b@example.com",
        phone: "+381 62 667 7788",
        investor_type: "buyer",
        created_at: "2024-06-05T13:45:00Z",
        building_id: "4",
        building_name: "Horizon Towers",
        block: "Tower B",
        unit: "B-504",
        area_m2: 85.0,
        delivery_period: "Q1 2026",
        purchase_value: 245000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-33",
        profile_id: "prof-33",
        full_name: "Pavle Panić",
        email: "pavle.p@example.com",
        phone: "+381 63 998 8877",
        investor_type: "buyer",
        created_at: "2024-06-10T11:20:00Z",
        building_id: "4",
        building_name: "Horizon Towers",
        block: "Tower B",
        unit: "B-505",
        area_m2: 52.0,
        delivery_period: "Q1 2026",
        purchase_value: 155000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-34",
        profile_id: "prof-34",
        full_name: "Anđela Arsić",
        email: "andjela.a@example.com",
        phone: "+381 64 332 2211",
        investor_type: "buyer",
        created_at: "2024-06-15T10:05:00Z",
        building_id: "4",
        building_name: "Horizon Towers",
        block: "Tower C",
        unit: "C-401",
        area_m2: 105.0,
        delivery_period: "Q1 2026",
        purchase_value: 310000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-35",
        profile_id: "prof-35",
        full_name: "Đorđe Đukić",
        email: "djordje.dj@example.com",
        phone: "+381 65 778 8877",
        investor_type: "buyer",
        created_at: "2024-06-20T16:10:00Z",
        building_id: "4",
        building_name: "Horizon Towers",
        block: "Tower C",
        unit: "C-402",
        area_m2: 78.0,
        delivery_period: "Q1 2026",
        purchase_value: 235000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-36",
        profile_id: "prof-36",
        full_name: "Valentina Vujić",
        email: "valentina.v@example.com",
        phone: "+381 61 445 6655",
        investor_type: "buyer",
        created_at: "2024-06-25T14:30:00Z",
        building_id: "1",
        building_name: "Avala Resort",
        block: "Block C",
        unit: "C-101",
        area_m2: 84.0,
        delivery_period: "Q4 2024",
        purchase_value: 158000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-37",
        profile_id: "prof-37",
        full_name: "Emilija Erceg",
        email: "emilija.e@example.com",
        phone: "+381 62 223 4422",
        investor_type: "buyer",
        created_at: "2024-07-01T09:50:00Z",
        building_id: "1",
        building_name: "Avala Resort",
        block: "Block C",
        unit: "C-102",
        area_m2: 58.0,
        delivery_period: "Q4 2024",
        purchase_value: 112000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-38",
        profile_id: "prof-38",
        full_name: "Kristina Krstić",
        email: "kristina.k@example.com",
        phone: "+381 63 112 2333",
        investor_type: "buyer",
        created_at: "2024-07-05T13:20:00Z",
        building_id: "2",
        building_name: "Skyline Plaza",
        block: "Tower West",
        unit: "W-2001",
        area_m2: 125.0,
        delivery_period: "Q2 2025",
        purchase_value: 385000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-39",
        profile_id: "prof-39",
        full_name: "Relja Raković",
        email: "relja.r@example.com",
        phone: "+381 64 887 7766",
        investor_type: "buyer",
        created_at: "2024-07-10T11:45:00Z",
        building_id: "2",
        building_name: "Skyline Plaza",
        block: "Tower West",
        unit: "W-2002",
        area_m2: 45.0,
        delivery_period: "Q2 2025",
        purchase_value: 135000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-40",
        profile_id: "prof-40",
        full_name: "Marija Marinković",
        email: "marija.m@example.com",
        phone: "+381 65 223 1100",
        investor_type: "buyer",
        created_at: "2024-07-15T09:05:00Z",
        building_id: "1",
        building_name: "Avala Resort",
        block: "Block A",
        unit: "A-501",
        area_m2: 92.0,
        delivery_period: "Q4 2024",
        purchase_value: 178000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-41",
        profile_id: "prof-41",
        full_name: "Todor Todorović",
        email: "todor.t@example.com",
        phone: "+381 61 776 5544",
        investor_type: "buyer",
        created_at: "2024-07-20T16:40:00Z",
        building_id: "4",
        building_name: "Horizon Towers",
        block: "Tower B",
        unit: "B-805",
        area_m2: 67.0,
        delivery_period: "Q1 2026",
        purchase_value: 205000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-42",
        profile_id: "prof-42",
        full_name: "Andrea Andrić",
        email: "andrea.a@example.com",
        phone: "+381 62 334 2211",
        investor_type: "buyer",
        created_at: "2024-07-25T14:15:00Z",
        building_id: "4",
        building_name: "Horizon Towers",
        block: "Tower B",
        unit: "B-806",
        area_m2: 115.0,
        delivery_period: "Q1 2026",
        purchase_value: 345000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-43",
        profile_id: "prof-43",
        full_name: "Gavrilo Gajić",
        email: "gavrilo.g@example.com",
        phone: "+381 63 998 1122",
        investor_type: "buyer",
        created_at: "2024-08-01T10:50:00Z",
        building_id: "2",
        building_name: "Skyline Plaza",
        block: "Tower East",
        unit: "E-101",
        area_m2: 180.0,
        delivery_period: "Q2 2025",
        purchase_value: 520000,
        purchase_currency: "EUR"
    },
    {
        id: "inv-44",
        profile_id: "prof-44",
        full_name: "Isidora Ignjatović",
        email: "isidora.i@example.com",
        phone: "+381 64 223 6677",
        investor_type: "buyer",
        created_at: "2024-08-05T13:30:00Z",
        building_id: "2",
        building_name: "Skyline Plaza",
        block: "Tower East",
        unit: "E-102",
        area_m2: 50.0,
        delivery_period: "Q2 2025",
        purchase_value: 155000,
        purchase_currency: "EUR"
    }
];
